NCRF.cpp
int GaborFilter(vector< vector< Mat >> &dstImg, const Mat srcImg, bool halfwave, float lamda, float sigma, vector< float > theta, vector< float > phi, float gamma, float bandwidth)
References GaborKernel2d.
Referenced by NonCRF.
int GaborFilterMulScale(vector< vector< Mat >> &dstImg, const Mat srcImg, bool halfwave, vector< float > lamda, vector< float > sigma, vector< float > theta, vector< float > phi, float gamma, float bandwidth)
References GaborKernel2d.
Referenced by NonCRF, NonCrf_fastener.
int GaborFilterMulScaleBend(vector< vector< Mat >> &dstImg, const Mat srcImg, bool halfwave, vector< float > lamda, vector< float > sigma, vector< float > theta, vector< float > phi, float gamma, float bandwidth)
References GaborKernel2d.
void PhaseSuppos(vector< Mat > &dstImg, const vector< vector< Mat >> &srcImg, int ntheta, int nphi, int supMethod)
Referenced by NonCRF, NonCrf_fastener.
void Inhibition(vector< Mat > &dstImg, vector< Mat > &srcImg, int inhibMethod, int supMethod, float sigma, float alpha, int k1, int k2)
References DogKernel2d.
Referenced by NonCRF, NonCrf_fastener.
void Inhibition(vector< Mat > &dstImg, vector< Mat > &srcImg, int inhibMethod, int supMethod, float sigma, const vector< Mat > &kernel)
void Inhibition(vector< Mat > &dstImg, vector< Mat > &srcImg, int inhibMethod, int supMethod, float sigma, const vector< Mat > &kernel, const vector< float > &coefs)
void ViewImage(Mat &dstImg, Mat &orienImg, const vector< Mat > &srcImg, const vector< float > theta)
Referenced by NonCRF, NonCrf_fastener.
void Thinning(Mat &dstImg, const Mat &srcImg, const Mat &orienMat)
Referenced by NonCRF, NonCrf_fastener.
void Hysteresis(Mat &srcImg, float tlow, float thigh)
Referenced by NonCRF, NonCrf_fastener.
void InvertImg(Mat &srcImg)
Referenced by NonCRF, NonCrf_fastener.
void Evaluate(float &p, float &efp, float &efn, const Mat &rstImg, const Mat &gtImg, int neigbSize)
Referenced by NonCRF.
float NonCRF(Mat srcImg, Mat gtImg)
References GaborFilterMulScale, Hysteresis, Inhibition, InvertImg, PhaseSuppos, Thinning, ViewImage.
Referenced by GaParWrapper::operator(), showResult.
float NonCRF(Mat srcImg, Mat gtImg, vector< Mat > kernel, bool isDisplay)
References Evaluate, GaborFilter, Hysteresis, Inhibition, InvertImg, PhaseSuppos, Thinning, ViewImage.
float NonCRF(Mat srcImg, Mat gtImg, const vector< Mat > &kernel, const vector< float > coefs, bool isDisplay)
References Evaluate, GaborFilter, Hysteresis, Inhibition, InvertImg, PhaseSuppos, Thinning, ViewImage.
Mat GaborKernel2d(float sigma, float lamda, float theta, float phi, float gamma, float bandwidth)
Referenced by CircleDetection, drawButterflyNCRF, foo, GaborFilter, GaborFilterMulScale, GaborFilterMulScaleBend.
Mat GaborKernel2d(float sigma, float lamda, float theta, float phi, float gamma, float bandwidth, float radiu)
References BendGabor2d.
Mat BendGabor2d(float sigma, float lamda, float theta, float phi, float gamma, float bandwidth, float radiu)
Referenced by GaborKernel2d.
Mat DogKernel2d(float sigma, int k1, int k2)
Referenced by drawButterflyNCRF, Ga_init, Inhibition.
Mat createFftImage(const Mat &srcImg, int fh, int fw)
Referenced by convolution.
Mat convolution(const Mat &srcImg, const Mat &filterKernel, const Mat &fftImg)
References createFftImage.
Mat NonCrf_fastener(Mat srcImg, int inhibModel, float tl, float th)
References GaborFilterMulScale, Hysteresis, Inhibition, InvertImg, PhaseSuppos, Thinning, ViewImage.
Referenced by main.
Mat drawButterflyNCRF()
References DogKernel2d, GaborKernel2d.
Referenced by main.