PostProgress
PostProgress::PostProgress()
PostProgress::~PostProgress()
void PostProgress::HTC(Mat &src, Mat &dst, int thHigh, int thLow)
References DFS.
void PostProgress::DFS(const Point point, Mat &img, Mat &visited, int th, int *flag)
Referenced by HTC.
void PostProgress::MySobel(Mat &src, Mat &dst, Mat &dstx, Mat &dsty)
void PostProgress::RamerFunc(double *xdata, double *ydata, int beginpoint, int endpoint, int *ResultArray, int &Index, double th)
Referenced by FittingDenosing.
void PostProgress::SortContours(vector< vector< Point > > &inCont, vector< vector< Point > > &outCont)
References splitContours.
void PostProgress::FindCross(const vector< Point > &inCnt, vector< int > &crossIdx)
References isNeigbour.
Referenced by splitContours.
void PostProgress::FindEndPoint(Mat &srcImg, vector< Point > &vEndPoints)
Referenced by EdgeTrack, RemoveBurr.
void PostProgress::FindCrossPoint(Mat &srcImg, vector< Point > &vCrossPoints)
References IsCrossPont.
Referenced by EdgeTrack, RemoveBurr.
bool PostProgress::IsCrossPont(const Mat &srcImg, Point pt)
Referenced by FindCrossPoint.
void PostProgress::RemoveBurr(Mat &srcImg, vector< Point > &vEndPoint, vector< Point > &vCrossPoint, int lenThresh=20)
Referenced by RemoveBurr.
void PostProgress::RemoveBurr(Mat &srcImg, int th)
References FindCrossPoint, FindEndPoint, RemoveBurr.
void PostProgress::EdgeTrack(Mat &srcImg, vector< vector< Point > > &vvPoints)
References FindCrossPoint, FindEndPoint.
void PostProgress::FittingDenosing(vector< vector< Point > > &srcVec, vector< vector< Point > > &dstVec, int lineArr[], double curRadio=20, double disTh=3)
References RamerFunc.
void PostProgress::Vec2Mat(vector< vector< Point > > &vvPoint, Mat &dstImg)
Point PostProgress::findEndPoints(vector< Point > &, int &)
bool PostProgress::isNeigbour(Point &a, Point &b, int isFourNeig)
Referenced by FindCross, getSingleCnt.
bool PostProgress::isNeigbour(const Point &a, const Point &b)
int PostProgress::distance(Point &, Point &)
void PostProgress::splitContours(vector< Point > &srcConts, vector< vector< Point > > &dstCnt)
References FindCross, getSingleCnt, removeRepeat.
Referenced by SortContours.
void PostProgress::removeRepeat(vector< Point > &)
Referenced by splitContours.
void PostProgress::getSingleCnt(int beginPointIdx, vector< Point > &inCnt, int *isVisited, vector< Point > &outCnt)
References isNeigbour.
Referenced by splitContours.