GA.cpp
Mat maxKer
Referenced by GA, Ga_fitness.
vector<float> avefit
vector<float> maxfit
int maxFitIndex
Referenced by Ga_fitness.
float wholeMax
Referenced by Ga_fitness.
void Ga_init(int maskSize, int ntheta, vector< individual > &population, int popSize)
References DogKernel2d.
Referenced by GA.
void Ga_fitness(const Mat &trainData1, const Mat &trainData2, const Mat groundTruth1, const Mat &groundTruth2, vector< individual > &population, vector< float > &fitValues, int kernelSize, int ntheta)
References maxFitIndex, maxKer, wholeMax.
Referenced by GA, Ga_select, maxFit.
void Ga_select(const Mat &trainData1, const Mat &trainData2, const Mat groundTruth1, const Mat &groundTruth2, vector< individual > &population, bool elitism, int kernelSize, int ntheta)
References Ga_fitness.
Referenced by GA.
void Ga_cross(vector< vector< float >> &population, double cross_rate, int crossMethod)
void Ga_cross2d(vector< individual > &population, double cross_rate, int kernelSize, int ntheta)
Referenced by GA.
void Ga_mutation(vector< individual > &popultion, double mutation_rate)
Referenced by GA.
void GA(Mat &trainData1, Mat &trainData2, Mat &groundTruth1, Mat &groundTruth2)
References Ga_cross2d, Ga_fitness, Ga_init, Ga_mutation, Ga_select, loadMask, maxKer, saveMask.
void loadImg(vector< Mat > &srcVec)
void loadMat(vector< Mat > &groundTruth)
void savePopulation(string fileName, const vector< vector< float >> &population)
void saveFitvalue(string fileNameAve, const vector< float > &avefit, const vector< float > maxfit)
void loadPopulation(string fileName, vector< vector< float >> &population)
void showResult(const vector< float > &population, int ntheta, const Mat &srcImg, const Mat &gtImg)
References NonCRF.
float maxFit(const Mat &trainData1, const Mat &trainData2, const Mat groundTruth1, const Mat groundTruth2, vector< individual > &population, int kernelSize, int ntheta, int &maxIndex)
References Ga_fitness.
void saveMask(const Mat &kernel, string fileName)
Referenced by GA.
void loadMask(Mat &kernel, int kersize, string fileName)
Referenced by GA.